name: BuildManylinux

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install depencecies
        run: |
          python -m pip install --upgrade pip
          pip install wheel twine
      - name: Build wheels
        uses: joerick/cibuildwheel@v1.11.0
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_ARCHS: x86_64
          CIBW_BUILD: cp36-manylinux_x86_64
          CIBW_BEFORE_ALL_LINUX: bash build_scripts/configure_linux.sh
          CIBW_BEFORE_BUILD_LINUX: bash build_scripts/build_wheel.sh
