envname: TurtlebotNavigateNoPhysicsEnv
model_id: Allensville
target_orn: [0, 0, 0.0]
target_pos: [0.0, 0.0, 0.0]
initial_orn: [0, 0, 4.71]
initial_pos: [0.0, 0.0, 0.0]
fov: 1.57
is_discrete: false

use_filler: true
display_ui: true
show_diagnostics: true
ui_num: 2
ui_components: [RGB_FILLED, DEPTH]
random:
  random_initial_pose : false
  random_target_pose : false
  random_init_x_range: [-0.1, 0.1]
  random_init_y_range: [-0.1, 0.1]
  random_init_z_range: [-0.1, 0.1]
  random_init_rot_range: [-0.1, 0.1]
  random_target_range: 0.1

output: [nonviz_sensor, rgb_filled, depth]
resolution: 256

speed:
  timestep: 0.01
  frameskip: 1

mode: gui #gui|headless
verbose: false