name: BuildManylinux

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6 ]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install depencecies
        run: |
          python -m pip install --upgrade pip
          pip install wheel twine
          pip install -r requirements.txt
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.11.0
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_ARCHS: x86_64
          CIBW_BUILD: cp36-manylinux_x86_64
          CIBW_MANYLINUX_X86_64_IMAGE: quay.io/pypa/manylinux2010_x86_64
          CIBW_BEFORE_ALL_LINUX: bash build_scripts/before_all_linux.sh
          CIBW_BEFORE_BUILD_LINUX: bash build_scripts/before_build_linux.sh
