name: BuildManylinux2010

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels
    runs-on: ubuntu-latest

    steps:
      - name: Increase disk space
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - name: Build
        run: |
          echo "Free space:"
          df -h
      - name: Start docker image
        run: |
          sudo docker run -i -t -v `pwd`:/io quay.io/pypa/manylinux2010_x86_64 /bin/bash
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Configure python environments
        run: |
          cd ..
          /bin/bash GibsonEnv/build_scripts/manylinux2010/setup_python_versions.sh
      - name: Configure system
        run: |
          cd ..
          /bin/bash GibsonEnv/build_scripts/manylinux2010/configure_linux.sh
      - name: Build sdist
        run: |
          export CC=/usr/lib64/openmpi/bin/mpicc
          pip3.6 install wheel
          pip3.6 install -r build_scripts/manylinux2010/requirements.txt
          python3.6 setup.py sdist
      - name: Build bdists
        run: |
          /bin/bash build_scripts/manylinux2010/build_bdists.sh
      - name: Upload to testpypi
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          pip3 install twine
          python3 -m twine upload --repository testpypi dist/gibson*.tar.gz --skip-existing
          python3 -m twine upload --repository testpypi wheelhouse/* --skip-existing
