name: BuildManylinux2010

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request]

jobs:
  build_wheels:
    name: Build manylinux2010 wheels
    runs-on: ubuntu-latest
    container: micheleantonazzi/manylinux-extended:manylinux2010_x86_64_extended_latest
    strategy:
      matrix:
        python_version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Configure system
        run: |
          cd ..
          /bin/bash GibsonEnv/build_scripts/manylinux2010/configure_linux.sh
      - name: Build sdist
        run: |
          export CC=/usr/lib64/openmpi/bin/mpicc
          pip${{ matrix.python_version }} install wheel
          pip${{ matrix.python_version }} install -r build_scripts/manylinux2010/requirements.txt
          python${{ matrix.python_version }} setup.py sdist
      - name: Build bdists
        run: |
          export CC=/usr/lib64/openmpi/bin/mpicc
          pip${{ matrix.python_version }} install -e .
          python${{ matrix.python_version }} setup.py bdist_wheel
          auditwheel repair dist/gibson-*-cp*
      - name: Upload to testpypi
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          pip${{ matrix.python_version }} install twine
          python${{ matrix.python_version }} -m twine upload --repository testpypi dist/gibson*.tar.gz --skip-existing
          python${{ matrix.python_version }} -m twine upload --repository testpypi wheelhouse/* --skip-existing